AWSTemplateFormatVersion: "2010-09-09"
Description: "gocontainer"
Parameters:
  IP8080:
    Type: String
  IP22:
    Type: String
  region:
    Type: String
  gszipbucketobject:
    Type: String
  ami:
    Type: String
  keypair:
    Type: String
Resources:
  gocontainersecgrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
#     This property must include the literal 'gocontainer' (see userdata/install).
      GroupDescription: gocontainersecgrp
  Server:
    Type: AWS::EC2::Instance
    Properties:
      Tags:
        - Key: Name
          Value: gocontainer
      ImageId: !Ref ami
      InstanceType: t2.micro
      KeyName:  !Ref keypair
      SecurityGroupIds: 
        - !Ref gocontainersecgrp
      IamInstanceProfile: go_cf_pwsh_gs
      UserData:
        Fn::Base64:
          Fn::Join:
            - ""
            -
              - "#!/bin/bash -ex\n" 
              - "yum install git -y\n"
              - "sudo -u ec2-user bash -c 'cd /home/ec2-user; git clone https://github.com/craigwongva/go-cf-pwsh-gs.git'\n"
              - "sudo -u ec2-user bash -c 'cd /home/ec2-user/go-cf-pwsh-gs; ./userdata/install "
              - !Ref IP8080
              - " "
              - !Ref IP22
              - " "
              - !Ref region
              - " "
              - !Ref gszipbucketobject
              - "'\n"
Outputs:
  InstanceID:
    Description: "The Instance ID"
    Value: !GetAtt Server.PublicIp

